# Generated by Django 4.1 on 2023-02-28 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('artist', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('level', models.IntegerField()),
                ('image', models.FileField(blank=True, null=True, upload_to='tab/image/')),
                ('price', models.PositiveIntegerField(default=300)),
                ('tab', models.FileField(blank=True, null=True, upload_to='tab/')),
                ('tab_image', models.FileField(blank=True, null=True, upload_to='tab_image/')),
                ('sale', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('division', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('tentative_sale', models.CharField(blank=True, max_length=150, null=True)),
                ('checkout_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MusicReleaseApp.items')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
