# Generated by Django 4.1 on 2023-02-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReleaseApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='tab_image',
        ),
        migrations.AddField(
            model_name='items',
            name='artwork',
            field=models.FileField(blank=True, null=True, upload_to='artwork/'),
        ),
        migrations.AddField(
            model_name='items',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
