# Generated by Django 4.1 on 2023-02-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReleaseApp', '0003_alter_items_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='publish',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
