# Generated by Django 4.1 on 2023-03-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReleaseApp', '0004_items_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='volume',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
