# Generated by Django 4.1 on 2023-03-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReleaseApp', '0006_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
